// Steam-style taxonomy for PixelVault.
// Derived from public Steam store search facets (genres / tags / features).
// See: https://store.steampowered.com/search (Narrow by tag / Genre facets)

const STEAM_GENRES = [
  'Action',
  'Adventure',
  'RPG',
  'Strategy',
  'Simulation',
  'Sports',
  'Racing',
  'Casual',
  'Indie',
  'Horror',
  'Puzzle',
  'Platformer',
  'Shooter',
  'Fighting',
  'Survival',
  'Souls-like',
  'Roguelike',
  'Roguelite',
  'Metroidvania',
  'Visual Novel',
  'Point & Click',
  'Tower Defense',
  'MOBA',
  'Battle Royale',
  'Free to Play',
  'Early Access',
  'Open World',
  'Cozy',
];

const STEAM_TAGS_POPULAR = [
  'Singleplayer',
  'Multiplayer',
  'Co-op',
  'Online Co-Op',
  'Local Co-Op',
  'Open World',
  'Story Rich',
  'Atmospheric',
  'Exploration',
  'Fantasy',
  'Sci-fi',
  'Pixel Graphics',
  'Anime',
  'Cute',
  'Funny',
  'Horror',
  'Survival',
  'Crafting',
  'Building',
  'Base Building',
  'Colony Sim',
  'Farming Sim',
  'Life Sim',
  'Racing',
  'Sports',
  'Puzzle',
  'Souls-like',
  'Roguelike',
  'Metroidvania',
  'Deckbuilding',
  'Turn-Based',
  'Real-Time',
  'Strategy RPG',
  'Action RPG',
  'JRPG',
  'CRPG',
  'Choices Matter',
  'Multiple Endings',
  'Character Customization',
  'Controller',
  'Great Soundtrack',
  'Replay Value',
  'Difficult',
  'Relaxing',
  'Family Friendly',
  'Moddable',
];

const STEAM_FEATURES = [
  'Single-player',
  'Online Co-op',
  'Local Co-op',
  'Cross-Platform Multiplayer',
  'Steam Achievements',
  'Steam Cloud',
  'Full controller support',
  'Partial Controller Support',
  'Steam Workshop',
  'Level Editor',
  'VR Supported',
  'Steam Deck Verified',
  'Cloud Saves',
  'Trading Cards',
];

const STEAM_PLATFORMS = ['Windows', 'Mac', 'Linux', 'Steam Deck', 'VR'];

const STEAM_SPECIALS = [
  { key: 'topsellers', label: 'Top Sellers', sort: 'popular' },
  { key: 'new', label: 'New & Trending', sort: 'newest' },
  { key: 'specials', label: 'Special Offers', onSale: '1' },
  { key: 'free', label: 'Free to Play', maxPrice: '0' },
  { key: 'deck', label: 'Steam Deck Verified', platform: 'Steam Deck' },
  { key: 'vr', label: 'VR Titles', platform: 'VR' },
];

module.exports = { STEAM_GENRES, STEAM_TAGS_POPULAR, STEAM_FEATURES, STEAM_PLATFORMS, STEAM_SPECIALS };
